### ISSUE TITLE
Do not run `Lint PR` workflow on automated PRs

### ISSUE THREAD

**Issue by janpio** [prisma/ecosystem-tests#697]
Dependabot and Renovate do not need proof that they did not touch the code.

**Comment by steebchen** [comment]
I don't get it

**Comment by janpio** [comment]
These Action runs seems to be superfluous:
![image](https://user-images.githubusercontent.com/183673/90675305-900e1f00-e25a-11ea-8084-fcb4fe45614e.png)
Dependabot and Renovate will not mess with our code.

As we had problems with Actions being overloaded with all the workflows started with all the PRs, this would be an easy way to cut down on that number.

**Comment by steebchen** [comment]
This workflow just runs semantic commit checks. It's the equivalent of the "Semantic Pull Request" app as a GitHub Actions. I don't believe it provides value to make exceptions for PRs just for this single workflow, especially because it is sometimes useful to have this check for dependency PRs since it detects the commit message style automatically and may misread it when there are some non-semantic commit messages.

**Comment by janpio** [comment]
So replacing the Action with the app would remove 50% of our Action runs here? Or was there a reason why we can not use that one here?

In the last week the Action runs got overwhelmed multiple times which required multiple hours to fix itself. If this ever happens at the time of a planned release, we are in trouble as there is nothing we can do to unblock this. Less Action runs are desirable here.

**Comment by steebchen** [comment]
We can use the app instead, but since we have like 30 check test runs, I'm not sure if that one test workflow helps... and it would still need to run to check if it actually needs run, so I'm afraid this will be some work without any real benefit.

**Comment by divyenduz** [comment]
Do we still want to do this?
